main:
  - name: "What is Flock?"
    pageRef: "/what-is-flock/"
    weight: 10
  - name: "Liberty Is Not the Price of Safety"
    pageRef: "/liberty-is-not-the-price-of-safety/"
    weight: 20
  - name: "The Ordinance"
    pageRef: "/the-ordinance/"
    weight: 30
  - name: "Take Action"
    pageRef: "/take-action/"
    weight: 40
  - name: "FAQ"
    pageRef: "/faq/"
    weight: 50
  - name: "Updates"
    pageRef: "/updates/"
    weight: 60
  - name: "About"
    pageRef: "/about/"
    weight: 70

footer:
  - name: "About"
    pageRef: "/about/"
    weight: 10
  - name: "GitHub"
    url: "https://github.com/simulacra10/gettheflockouttahere.org"
    weight: 20
  - name: "MIT License"
    url: "https://github.com/simulacra10/gettheflockouttahere.org/blob/main/LICENSE"
    weight: 30
